### ISSUE TITLE
problem virus all virtualtotal.

### ISSUE THREAD

**Issue by Benzitczo** [Fody/Costura#889] opened 2023-05-28 09:45 UTC
https://github.com/Fody/Costura/issues/294 check before

and same here: https://www.virustotal.com/gui/file/77a9e5d9263942de65f06f0152c34543ccd8838bf6e5d9119845b75e1ebf4e6f?nocache=1
![image](https://github.com/Fody/Costura/assets/36309164/9bdb040f-3a7a-4e11-8639-040a14cacf4c)

no working nothing bad. unistall costura fody or solution have how solution.

**Comment by tom-englert** [comment] 2023-05-28 14:45
Duplicate of #294

**Closed** 2023-05-28 14:45 UTC
