### ISSUE TITLE
Sunset/Obsolete Costura?

### ISSUE THREAD

**Issue by SimonCropp** [Fody/Costura#442] opened 2019-10-12 00:28 UTC
In dotnet core 3 there are two new features

 * [Single-file executables](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#single-file-executables)
 * [Assembly linking](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#assembly-linking)

With these features included in the dotnet tool set, the value proposition of Costura is greatly diminished. With that in mind I think long term Costura should cease to be used as people transition over.

Please comment with any input.

Plan:

 * disable issues
 * PR will still be accepted but only for bug fixes
 * add note to readme
 * add note to nuget description
 * write a warning in MsBuild

**Comment by distantcam** [comment] 2019-10-12 14:57
Yes Yes Yes!

The design docs for single-file exes mentions Costura a lot, suggesting Microsoft also considers it a Costura killer.

About the only scenarion that Costura supports that single-file doesn't is single-file libraries. But I was never a fan of using Costura for that so 👍 to sunsetting Costura.

**Comment by tom-englert** [comment] 2019-10-12 15:07
Yes, for **LONG** term this is true. 
Anyhow there has not been any feature development in the near past, and only very few maintenance, so just leaving it as it is should fit.

**Comment by ltrzesniewski** [comment] 2019-10-12 18:47
I wouldn't mind.

To me it looks like Costura gets more *"bad"* issues raised on GitHub than all the other Fody addins combined, so I understand why you'd want to obsolete it.

**Comment by SimonCropp** [comment] 2019-10-29 02:18
one more nail in the coffin https://github.com/Fody/Costura/issues/454

**Comment by SimonCropp** [comment] 2019-10-29 02:20
@Logerfo i suggest you raise that with the MS team.

**Comment by SimonCropp** [comment] 2019-10-29 02:24
I am going to pull the trigger on this. plan updated above

**Comment by SimonCropp** [comment] 2019-10-29 02:25
@GeertvanHorrik can u confirm that plan. i dont think it should break your use case

**Comment by GeertvanHorrik** [comment] 2019-10-29 09:49
If I take over ownership, can it stay alive? I am happy to explain why we need it to stay alive (for lib projects) and to answer all questions.

**Comment by SimonCropp** [comment] 2019-10-29 11:34
@GeertvanHorrik are you sure you want to go to that effort?

**Comment by BobbyCannon** [comment] 2019-10-29 11:49
@SimonCropp As an Open Source maintainer I totally understand your desire to sunset this project. But like @GeertvanHorrik suggest, I also have a fork of this repo that I maintain (heavily edited and customized). I monitor this project for updates / ideas. 

I'm currently in the process of migrating "all the things" to .NET Core and it's a much bigger project that I thought. It's not a lift and shift for sure. I think it would be worth someone maintaining just for people not ready to move to newer platforms or that just doesn't have time to.

**Comment by BobbyCannon** [comment] 2019-10-29 11:52
I guess the point I was trying to make above is that Costura isn't obsolete for full framework. I think it will be needed for many more years. I personally will be moving on to the new framework but could see Costura staying alive in maintenance until the world catches up with .NET Core 3 or .NET 5 (coming 2020).

**Comment by GeertvanHorrik** [comment] 2019-10-29 12:01
> @GeertvanHorrik are you sure you want to go to that effort?

Basically any request would be closed as "won't fixed" unless it affects the current inner workings and/or embedding libs into libraries. I don't see that as a burden (but I might be underestimating :-) )

**Comment by SimonCropp** [comment] 2019-11-02 22:31
@Logerfo 

> As far as I can see, there is no option to publish a single-file executable containing only the third-party references, but always with the framework references as well, which makes the file very larger. 

i think this is what you want https://github.com/SimonCropp/NetCoreConsole#single-exe-and-framework-dependent  ?

**Comment by SimonCropp** [comment] 2019-11-02 22:34
@GeertvanHorrik happy to add you as a maintainer irrespective of the decision here. (sent you an invite)

> Basically any request would be closed as "won't fixed" unless it affects the current inner workings and/or embedding libs into libraries. I don't see that as a burden (but I might be underestimating

That is the plan. but until the project is marked as "being deprecated" people will still use it and demand things be fixed.

**Comment by GeertvanHorrik** [comment] 2019-11-03 15:42
If I understand correctly (correct me if I'm wrong!), we'll (as in I, nothing for you to spent hours on) do the following:

- [ ] Add me as maintainer. I will primarily do the maintenance on this weaver so it's out of (all of) your hands
- [ ] Update the readme to explain why this weaver has been put from "active development" to "maintenance" mode. It'll boil down to a list of supported scenarios, and I will add more exceptions to this list when we hit them

Any other things I'm missing out or you'd like to see different?

**Comment by Logerfo** [comment] 2019-11-04 12:47
@SimonCropp yes, thank you. The problem is that even the framework dependent single executable is also platform dependent. See dotnet/coreclr#27528.

**Comment by GeertvanHorrik** [comment] 2019-11-13 16:09
I've added the maintenance mode note to the readme. I think we all agree that this package should go into maintenance mode and I will take care of the remaining issues.

Thanks everyone who has contributed to both this discussion and Costura in general. I'll probably forget some important people, but especially @SimonCropp , @distantcam and @tom-englert !

**Closed by GeertvanHorrik** 2019-11-13 16:09 UTC

**Comment by andrewsav-datacom** [comment] 2019-12-05 18:07
The problem with single-file executable. that it packages the whole .net framework into that file. The whole bloody framework. So if with costura I get 3.5MB executable with .net build-in feature I get 160MB one.

It is unfortunate that the maintainers no longer have the drive to maintain and resolve outstanding issues (VB support, service support, limited cross-platform support, where practical) and focusing on the use case that is probably relevant to them, but unless some one steps up to do that, that's the way it is.

This just to voice, that costura's features is NOT obsolete, and it DOES provide value over single-file executables. But burn out after many years of maintaining the project is also understandable.

**Comment by Logerfo** [comment] 2019-12-05 18:12
@andrewsav-datacom the feature request you're looking for is being tracked by dotnet/coreclr#27528.

**Comment by SimonCropp** [comment] 2019-12-05 21:47
@andrewsav-datacom there is also framework dependent deployments https://github.com/SimonCropp/NetCoreConsole#framework-dependent

**Comment by SimonCropp** [comment] 2019-12-05 21:48
@andrewsav-datacom BTW If you are using fody i would have expected to see you in the list of patrons? https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md

**Comment by AndrewSav** [comment] 2019-12-05 21:54
@SimonCropp yeah until today I was not aware of the "business model". Reading some other issues I now see what happened. In any case it seems moot going forward.

**Comment by SimonCropp** [comment] 2019-12-05 22:01
@AndrewSav i suggest you look through your other open source projects. a significant number of projects now have funding models to try and cover the significant expense of maintaining open source. one approach you can look at is to use https://backyourstack.com/

**Comment by AndrewSav** [comment] 2019-12-05 22:06
Thank you, for your suggestion, @SimonCropp.
