### ISSUE TITLE
NuGet throws error

### ISSUE THREAD

**Issue by jakeharlan** [Fody/Costura#192] opened 2017-05-02 13:32 UTC
> Install-Package Costura.Fody

Attempting to resolve dependency 'Fody (≥ 2.0.6)'.
External packages cannot depend on packages that target projects.

Using VS 2013 with all latest updates
Package Manager Console Host Version 2.12.0.817

**Comment by jvinel** [comment] 2017-05-04 13:27
Same issue here VS 2013 with all latest updates.

**Comment by teodepap** [comment] 2017-05-07 08:31
I face the same issue as well with VS 2013. Previous version worked fine.

**Comment by Xan-Kun** [comment] 2017-05-10 14:06
Same issue here. VS2013 all updates (incl. nuget package manager).

**Comment by Xan-Kun** [comment] 2017-05-11 15:25
Is there a way to install an older version as a workaround?

**Comment by jakeharlan** [comment] 2017-05-11 15:39
By this thread it looks like you can check-out previous versions for almost any project.
http://rayshobby.net/how-to-check-out-a-previous-version-from-github-repository/

**Comment by Xan-Kun** [comment] 2017-05-11 16:05
Hi @jakeharlan  and thanks for the answer! I just f*?§$% up my whole workspace: When I uninstall Fody (2.0.7) it doesn't  find any references at all anymore :-) 
The installation of older versions seems to be supported via GUI in VS2015, in VS2013 there is still the nuget command line and `-Version`.
Right now I am trying to figure out, how to get it running again. :-)

**Comment by jakeharlan** [comment] 2017-05-11 16:15
I did not try the previous version, yet (might not given your results).
Luckily I use source control so I can always wipe out my local changes.
I feel your pain.  Good luck!

**Comment by Xan-Kun** [comment] 2017-05-11 16:16
Ok, I am lost here.
I have Fody (without Cosutra) installed and it compiles, when I remove Fody with Nuget Package Manager, no dependecies can be found, not even `Object` and I get the error message

> Error	1	This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Fody.2.0.7\build\portable-net+sl+win+wpa+wp\Fody.targets.	C:\dev2\MyProject.csproj	195	Program

I tried the mentioned package restore to no avail.
Any ideas on what I can do except creating a new workspace?
Any hint will be much appreciated :-)

**Comment by jakeharlan** [comment] 2017-05-11 16:18
Not sure what you mean by 'create a new workspace', but I think that if you do not have the package somewhere local on your machine and you cannot download the previous version then you are s.o.l.
Can you download the previous version directly from the GitHub repository?  Meaning you don't go through Visual Studio.
I probably will not get back to this project until next week.

**Comment by Xan-Kun** [comment] 2017-05-11 16:22
It seems to work again, there was some leftover in the csproj file and I had to delete the cached in the obj folder. No Costura still, but at least it compiles again.

**Comment by Xan-Kun** [comment] 2017-05-11 16:34
I can confirm that
`Install-Package Costura.Fody -Version 1.4.0`
works just fine.

**Comment by Xan-Kun** [comment] 2017-05-11 16:37
@jakeharlan Thank you so much for your nice words. If you ever get to fix this and you need any help please let me know, as for now, I am happy that it works again :-)

**Comment by Xan-Kun** [comment] 2017-05-11 16:40
BTW, I think the problem started when I tried to install JSON.Net (it totally made nuget manager flip out :-) ). That was before I found out, that you don't have to install JSON.Net anymore, as the already is a version available in VS2013.

**Comment by VFansss** [comment] 2017-05-16 11:09
@Xan-Kun I have the same problem.

I compiled my project and all was working correctly. I went to take a tea and at my return VS2013 give me the same error.

I've installed the 1.4.0 version thank to you but it worked for only for one compile. Than it does the same things. I've solved pressing "COMPILE -> Clear Solution" in VS2013 menu, the one on the top (is the third option in compile menu),

I hope I can help someone that come here, like me!

**Comment by jakeharlan** [comment] 2017-05-16 11:27
Install-Package Costura.Fody -Version 1.4.0 
If it helps anyone...you need to overwrite existing FodyWeavers.xml when prompted.
First time around I did not override the file and got a build error on Mono.Cecil.


PM> Install-Package Costura.Fody -Version 1.4.0
Attempting to resolve dependency 'Fody (≥ 2.0.4)'.
Installing 'Fody 2.0.4'.
Successfully installed 'Fody 2.0.4'.
Installing 'Costura.Fody 1.4.0'.
Successfully installed 'Costura.Fody 1.4.0'.
Adding 'Fody 2.0.4' to MyProject.
File Conflict
File 'FodyWeavers.xml' already exists in project 'MyProject'. Do you want to overwrite it?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [?] Help (default is "N"):Y
Overwrite existing file 'FodyWeavers.xml'.
Successfully added 'Fody 2.0.4' to MyProject.
Adding 'Costura.Fody 1.4.0' to MyProject.
Successfully added 'Costura.Fody 1.4.0' to MyProject.
RemoveForceProjectLevelHack
Update-FodyConfig
Upgrade detected. Restoring content for Costura
Flushing environment variables
Fix-ReferencesCopyLocal Costura.Fody

**Comment by Xan-Kun** [comment] 2017-05-16 21:10
@VFansss Glad to here I am not the only one and most of all, that you also got it fixed ;-)
Newtonsoft.JSON is part of VS2013 with my installation (and I am not the quickest when it comes to updates :-) ...).
I had to include it in the Reference Manager (Refernces -> Add Reference)
via
`Assemblies -> Framework -> Extensions -> Json.NET`
I think the name is terrible (even the capitalization is just wrong :-) ) and when you select it, it finally says "Created by: Newtonsoft" on the right.
Took me quite a while to figure this out and I *?%& up my workspace pretty nicely while trying to get it to work. Cosura was just colateral.

**Comment by KingzGambit** [comment] 2017-05-16 22:13
I am still having the same issue with Costura.Fody 1.4.1

**Comment by Xan-Kun** [comment] 2017-05-17 02:52
@KingzGambit Yeah, I tried some other approaches and it seems 1.4.1 will not work. Unfortunately, I have absolutely no clue wht could cause this, so I guess we have to stick with 1.4.0.
If you can find out more or need any help, please let me know. I would love to help, I'm just too new to the whole NuGet thingy.

**Comment by SimonCropp** [comment] 2018-04-04 13:05
this should be fixed in v2

**Closed by SimonCropp** 2018-04-04 13:05 UTC
