### ISSUE TITLE
Cannot build using dotnet on build server

### ISSUE THREAD

**Issue by StephenDrewLDS** [Fody/Costura#193] opened 2017-05-02 19:30 UTC
Hello,

I have a net40 vs2017-csproj project using Costura (1.4.1; Fody 2.0.6).  It builds fine in vs2017, but when I try to build it using `dotnet` (and by implication MsBuild15) on the build server, it fails.  I can get it to fail locally on my machine too by trying to build it using `dotnet build`:

```
> dotnet build XXX.sln

Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

XXXX\.nuget\packages\fody\2.0.6\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4062: The "Fody.WeavingTask" task could not be loaded from the assembly XXXX\.nuget\packages\fody\2.0.6\build\portable-net+sl+win+wpa+wp\..\..\\Fody.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [XXXX.csproj]

Build FAILED.

XXXX\.nuget\packages\fody\2.0.6\build\portable-net+sl+win+wpa+wp\Fody.targets(53,5): error MSB4062: The "Fody.WeavingTask" task could not be loaded from the assembly XXXX\.nuget\packages\fody\2.0.6\build\portable-net+sl+win+wpa+wp\..\..\\Fody.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [XXXX.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.68
```

Any ideas how I can get `dotnet` to build this?

Thanks

**Comment by dipdapdop** [comment] 2017-06-08 14:19
Yeah, me too on this:
`Microsoft (R) Build Engine version 15.1.1012.6693`
```
XXX\packages\fody\2.0.6\build\netstandard1.4\Fody.targets(53,5): error MSB4062: The "Fody.WeavingTask" task could not be loaded from the assembly XXX\packages\fody\2.0.6\build\netstandard1.4\..\..\\Fody.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [XXX.csproj]
```

**Comment by distantcam** [comment] 2017-06-08 14:22
This is a duplicate of Fody/Fody#330

**Comment by StephenDrewLDS** [comment] 2018-01-10 17:26
Not sure why this is closed as a duplicate.   Fody appears to have been updated, but Costura still not working?

**Comment by techgeek03** [comment] 2018-02-05 09:59
Same problem here I'm using Fody 2.3.25

**Comment by SimonCropp** [comment] 2018-04-04 12:53
fixed in v2

**Closed by SimonCropp** 2018-04-04 12:53 UTC
