### ISSUE TITLE
Odd Costura build error

### ISSUE THREAD

**Issue by bencyoung** [Fody/Costura#253] opened 2018-01-19 12:18 UTC
I'm getting a weird error trying to use Costura

```
C:\Users\Ben.Young\.nuget\packages\costura.fody\1.6.2\build\dotnet\Costura.Fody.targets(14,5): error MSB4062: The "Costura.Tasks.FilterReferenceCopyLocalPaths" task could not be loaded from the assembly C:\Users\Ben.Young\.nuget\packages\costura.fody\1.6.2\build\dotnet\..\..\\Costura.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [F:\Dev\RiskCore\f-risk-core\src\Services\Authenticator\F.Risk.Core.AuthenticatorService.csproj]
```

when running "dotnet build" 

```
F:\Dev\RiskCore\f-risk-core>dotnet --version
2.0.2
```

The dll it's looking for is definitely in C:\Windows\Microsoft.NET\Framework64\v4.0.30319

**Comment by bencyoung** [comment] 2018-01-19 15:42
It appears to be because of [https://github.com/dotnet/sdk/issues/1870](this dotnet issue) but I'm not sure if the correct fix is for dotnet to add the utilities, or Costura to migrate away from using the helpers

**Comment by bencyoung** [comment] 2018-01-22 09:24
Looks like it's expected that dotnet dosn't allow the utilities to be used

**Comment by poke** [comment] 2018-02-07 23:12
This appears to be a duplicate of #193 which has been reopened.

**Comment by SimonCropp** [comment] 2018-04-04 12:59
fixed in v2

**Closed by SimonCropp** 2018-04-04 12:59 UTC
